name: Release Chrome Extension

on:
  push:
    branches:
      - master
    paths:
      - "manifest.json"
      - "src/**"
      - "icon.png"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from manifest
        id: get-version
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create ZIP file
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          EXTENSION_NAME="enable-statut-mandat-pfo-v$VERSION.zip"
          zip -r $EXTENSION_NAME manifest.json src/ icon.png
          echo "extension_path=$EXTENSION_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          name: Release v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          files: ${{ env.extension_path }}

      - name: Update the update.xml file
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          cat <<EOF > update/update.xml
          <?xml version='1.0' encoding='UTF-8'?>
          <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
            <app appid='enable-statut-mandat-pfo@extension-id'>
              <updatecheck codebase='https://github.com/ItsZeusX/WE-Extention/releases/download/v$VERSION/enable-statut-mandat-pfo-v$VERSION.crx' version='$VERSION' />
            </app>
          </gupdate>
          EOF
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add update/update.xml
          git commit -m "Update version to $VERSION in update.xml [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"
