name: Release Chrome Extension

on:
  push:
    branches:
      - master
    paths:
      - "manifest.json"
      - "src/**"
      - "icon.png"

permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from manifest
        id: get-version
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create ZIP file
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          EXTENSION_NAME="enable-statut-mandat-pfo-v$VERSION.zip"
          zip -r $EXTENSION_NAME manifest.json src/ icon.png
          echo "extension_path=$EXTENSION_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          name: Release v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          files: ${{ env.extension_path }}
          
      - name: Update the update.json file
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          jq --arg version "$VERSION" \
             --arg download_url "https://github.com/ItsZeusX/WE-Extention/releases/download/v$VERSION/enable-statut-mandat-pfo-v$VERSION.zip" \
             '.addons["enable-statut-mandat-pfo@extension-id"].updates[0].version = $version | .addons["enable-statut-mandat-pfo@extension-id"].updates[0].update_link = $download_url' \
             update/update.json > update/update.json.tmp
          mv update/update.json.tmp update/update.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add update/update.json
          git commit -m "Update version to $VERSION in update.json [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"
